Network: 
  name: DeepLabv3Plus
  num_class: 19

EMA:
  alpha: 0.99

Optim:
  lr: 6.4e-3
  weight_decay: 5e-4

Lr_Scheduler:
  name: PolyLR
  step_size: 90
  gamma: 0.1

Dataset:
  name: CityScapes
  data_dir: /
  txt_dir: /
  num_labels: 372
  batch_size: 4
  mix_mode: cutmix
  crop_size: !!python/tuple [769,769]
  scale_size: !!python/tuple [0.5,2.0]

Training_Setting:
  epoch: 200
  save_dir: ./checkpoints

Seed: 3407

Ramp_Scheduler:
  begin_epoch: 0
  max_epoch: 200
  max_value: 1.0
  min_value: 0
  ramp_mult: -5.0

Loss:
  is_available: True
  warm_up: 0
  un_threshold: 0.97
  strong_threshold: 0.97
  weak_threshold: 0.7
  temp: 0.5
  num_queries: 256
  num_negatives: 512
  alpha: 0.99

Distributed:
  world_size: 4
  gpu_id: 0,1,2,3